# Generated by Django 2.1.5 on 2019-01-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
