# Generated by Django 2.1.5 on 2019-01-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('art', models.ImageField(upload_to='')),
                ('about', models.TextField()),
                ('details', models.CharField(max_length=255)),
            ],
        ),
    ]
