# Generated by Django 2.1.5 on 2019-01-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='works',
            options={'verbose_name_plural': 'Works'},
        ),
    ]
