# Generated by Django 2.1.5 on 2019-01-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20190108_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='medium',
            field=models.CharField(choices=[('Digital', 'Digital'), ('Traditional', 'Traditional')], default='Traditional', max_length=50),
        ),
    ]
